server:
  port: 8089

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: ruuniv-gateway-server

  cloud:
    gateway:
      routes:
        - id: ruuniv-verification-server
          uri: lb://RUUNIV-VERIFICATION-SERVER
          predicates:
            - Path=/verification-api/**
          filters:
            - RewritePath=/verification-api/(?<segment>.*), /$\{segment}
            - name: AuthenticationFilter
              args:
                - requiredRole: ROLE_USER

        - id: ruuniv-statistics-server
          uri: lb://RUUNIV-STATISTICS-SERVER
          predicates:
            - Path=/statistics-api/**
          filters:
            - RewritePath=/statistics-api/(?<segment>.*), /$\{segment}
            - name: AuthenticationFilter
              args:
                - requiredRole: ROLE_USER

      default-filters:
        - name: LoggingFilter


secret:
  key: asdfzxcqweasdzxcasdqweqwdasdasdxzczxczxczxczxczxcascsa